# This rule is not used by the project k8s-operator-deploy-scaler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over api.scaler.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator-deploy-scaler
    app.kubernetes.io/managed-by: kustomize
  name: scaler-admin-role
rules:
- apiGroups:
  - api.scaler.com
  resources:
  - scalers
  verbs:
  - '*'
- apiGroups:
  - api.scaler.com
  resources:
  - scalers/status
  verbs:
  - get
